### PR TITLE
added keras integration and example

### PR DESCRIPTION
**Pull request by dlfelps**

### CODE REVIEW

**Comment by d6tdev** [comment]
great stuff thanks! You want to write a kdnuggets/towards data science blog post?

**Comment by d6tdev** [comment]
added to docs https://d6tflow.readthedocs.io/en/latest/targets.html#keras-model-targets

**Comment by dlfelps** [comment]
I am too busy at the moment to write a blog post, but feel free to use the example I included if you want to. Thanks for the cool project and I will keep contributing different target types as I write them.

**Comment by d6tdev** [comment]
No worries and new target types are even better!

**Pull request merged**
